name: sync_timer
description: "Server Sync Calculator"
version: 1.1.3

homepage: https://github.com/BatuhanSunar/sync_timer
repository: https://github.com/BatuhanSunar/sync_timer
issue_tracker: https://github.com/BatuhanSunar/sync_timer/issues

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #UTILS
  shared_preferences: ^2.5.1
  intl: ^0.20.2
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
